n=tuple()
t=int(input("how many no.s do you want to add:"))
for i in range (t):
    l=int(input())
    n=n+(l,)
print(n)
print("Sum of the given tuples:")
a=sum(n)
print(a)
print("Max value is:")
print(max(n))
print("Min value is:")
print(min(n))
print("mean of the given input is:")
print(a/t)
